/*
 * Welcome to ugly hack, because dokka generates the style.css one level outside the rest of the documentation
 * and that doesn't play well with github pages.
 */
import java.io.File
import  groovy.io.FileType

def docsFolder = new File("docs")
def kavanzaFolder = new File(docsFolder, "kavanza")

// traverse all files (not directories) in the docs/kavanza folder as generated by dokka (and later moved)
// create corresponding folder and file for each file in docs, without the kavanza folder
// rewrite every reference to the style.css file to be one folder less, i.e. ../style.css -> style.css and ../../style.css -> ../style.css
// delete each file original file and delete the kavanza folder.
kavanzaFolder.traverse([type: FileType.FILES]) {
    println it.path - "docs\\kavanza\\"
    def relPath = it.path - "docs\\kavanza\\"
    def newFile = new File(docsFolder, relPath)
    def newFolder = new File(newFile.path - newFile.name)
    newFolder.mkdirs()
    newFile.createNewFile()
    newFile.text = it.text.replaceAll(/(\.\.\/)+style\.css/) { all, _ ->
        all - "../"
    }
    it.delete()
}
kavanzaFolder.deleteDir()